#!/bin/bash

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" # http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in

source $SCRIPTDIR/../util
source $SCRIPTDIR/../CONFIG

# Takes a MODLIST and a REMAININGMODS and composes a brief message
function compose-message() {
    MODLIST="$1"
    shift
    REMAININGMODS="$*"

    echo "Hello,"
    echo
    echo "The following mods from your watchlist are available for the current KSP release:"
    echo "$(tab-list "$MODLIST")"
    echo

    if [[ -z "$REMAININGMODS" ]]
    then
        echo "There are no mods left in your watchlist!"
        echo "You have been unsubscribed. For more updates, create a new watchlist."
    else
        echo "The following mods remain on your watchlist:"
        echo "$(tab-list "$REMAININGMODS")"
    fi

    echo
    echo "Bye!"
}

# Takes an EMAIL and a MESSAGE then sends it out
function send-message() {
    EMAIL=$1
    shift
    MESSAGE="$*"

    echo "$MESSAGE" | mail -s "You have mods!" $EMAIL
}

# Main
[[ ! -e $USERSTORE ]] && mkdir -p $USERSTORE

while true
do
    date

    AVAILABLEMODS=$(cat $LATESTLIST | sed 's/ //g' | sed '/^\s*$/d' | sort | uniq)

    cd $USERSTORE
    USERLIST=$(ls -l | awk '{ print $NF }' | grep '@' | grep -v 'bak$')

    for USER in $USERLIST
    do
        echo "Processing $USER"

        USERBAK=$USER.bak
        cp $USER $USER.bak

        USERDATA=$(cat $USER | grep -v ' ')

        SUBSCRIPTION=$(cat $USER | sed 's/ //g' | sed '/^\s*$/d' | sort | uniq)
        # TODO Handle removal better

        UPDATEDMODS=$(get-common "$SUBSCRIPTION" "$AVAILABLEMODS")

        if [[ ! -z "$UPDATEDMODS" ]] 
        then
            echo "Updated mod(s) found!"
            echo "$(tab-list "$UPDATEDMODS")"

            UPDATEDSUB=$(filter-list "$SUBSCRIPTION" "$AVAILABLEMODS")
            send-message $USER "$(compose-message "$UPDATEDMODS" "$UPDATEDSUB")"

            if [[ ! -z "$UPDATEDSUB" ]]
            then
                echo "$UPDATEDSUB" > $USER
            else
                echo "Watchlist complete. Deleting user"
                rm -f $USER
            fi
        fi

        rm $USER.bak
    done

    echo "Sleeping for a bit"
    sleep 900
done
