#!/bin/bash

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" # http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in

source $SCRIPTDIR/../CONFIG

# Takes LIST and EXCLUSIONLIST. Masks away all EXCLUSIONLIST from LIST.
function filter-list() {
    LIST=$(echo "$1" | sort)
    EXCLUSIONLIST=$(echo "$2" | sort)

    diff <(echo "$LIST") <(echo "$EXCLUSIONLIST") | grep "<" | sed 's/^< //g' | sort | uniq
}

# Takes LIST and OTHERLIST. Finds the elements they have in common.
function get-common() {
    LIST=$(echo "$1" | sort)
    OTHERLIST=$(echo "$2" | sort)

    comm -12 <(echo "$LIST") <(echo "$OTHERLIST") | sort | uniq
}

# Takes a MODLIST and composes a brief message
function compose-message() {
    MODLIST="$1"

    echo "Hello,"
    echo ""
    echo "The following mods have been updated:"
    echo "$MODLIST"
    echo
    echo "Bye!"
}

# Takes an EMAIL and a MESSAGE then sends it out
function send-message() {
    EMAIL=$1
    shift
    MESSAGE="$*"

    echo "$MESSAGE" | mail -s "You have mods!" $EMAIL
}

# Main
[[ ! -e $USERSTORE ]] && mkdir -p $USERSTORE

while true
do
    date

    AVAILABLEMODS=$(cat $REFERENCELIST)

    cd $USERSTORE
    USERLIST=$(ls -l | awk '{ print $NF }' | grep '@' | grep -v 'bak$')

    for USER in $USERLIST
    do
        echo "Processing $USER"

        USERBAK=$USER.bak
        cp $USER $USER.bak

        USERDATA=$(cat $USER | grep -v ' ')

        SUBSCRIPTION=$(cat $USER | sort | uniq)

        UPDATEDMODS=$(get-common "$SUBSCRIPTION" "$AVAILABLEMODS")

        if [[ ! -z "$UPDATEDMODS" ]] 
        then
            send-message $USER "$(compose-message "$UPDATEDMODS")"
            UPDATEDSUB=$(filter-list "$SUBSCRIPTION" "$AVAILABLEMODS")
            echo "$UPDATEDSUB" > $USER
        fi

        rm $USER.bak
    done

    sleep 1
done
