#!/bin/bash

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" # http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in

source $SCRIPTDIR/../CONFIG

# Configurations
NOTIFICATIONPERIOD="900"

mkdir -p $SUBSCRIBERSTORE &>/dev/null

while true
do
    LOADEDVERSION=$(cat $VERSIONFILE | head)

    SUBSCRIBERS=$(ls $SUBSCRIBERSTORE | awk -F'/' '{ print $NF }')
    AVAILABLEMODS=$(cat $LATESTLIST | sed 's/ //g' | sed '/^\s*$/d' | sort | uniq)

    if [[ -z "$ACTIVEVERSION" ]]
    then
        ACTIVEVERSION=$LOADEDVERSION
    fi

    if [[ "$ACTIVEVERSION" != "$LOADEDVERSION" ]]
    then
        echo "Detected new version $ACTIVEVERSION -> $LOADEDVERSION"

        ACTIVEVERSION=$LOADEDVERSION

        # Sync subscriber data, notify subscriber of version update and reload data
        for SUBSCRIBER in $SUBSCRIBERS
        do
            echo "Notifcation service notifying \"$SUBSCRIBER\" of version change"

            $SUBSCRIBERSTORE/$SUBSCRIBER/version-change
        done
    fi

    for SUBSCRIBER in $SUBSCRIBERS
    do
        echo "Notification service processing \"$SUBSCRIBER\""
        # TODO: Checks

        NOTIFIERS=$(cat $SUBSCRIBERSTORE/$SUBSCRIBER/notifiers)

        for NOTIFIERDATA in $NOTIFIERS
        do
            TYPE=$(echo $NOTIFIERDATA | awk -F':' '{ print $1 }')
            SUBSCRIBERDIR=$SUBSCRIBERSTORE/$SUBSCRIBER

            CMD=". $SCRIPTDIR/$TYPE $SUBSCRIBERDIR"

            eval $CMD
        done

        echo
    done

    echo "Sleeping $NOTIFICATIONPERIOD"
    sleep $NOTIFICATIONPERIOD
done
