#!/bin/bash

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" # http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in

source $SCRIPTDIR/../CONFIG

# Configurations
NOTIFICATIONPERIOD="900"

# Load SUBSCRIBER to the workspace
function load() {
    local SUBSCRIBER=$1
    rm -rf $SUBSCRIBERWORKSPACE/$SUBSCRIBER
    cp -r $SUBSCRIBERSTORE/$SUBSCRIBER $SUBSCRIBERWORKSPACE/$SUBSCRIBER
}

# Persist SUBSCRIBER to store
function persist() {
    local SUBSCRIBER=$1
    rm -rf $SUBSCRIBERSTORE/$SUBSCRIBER
    cp -r $SUBSCRIBERWORKSPACE/$SUBSCRIBER $SUBSCRIBERSTORE/$SUBSCRIBER
}

mkdir -p $SUBSCRIBERSTORE &>/dev/null
mkdir -p $SUBSCRIBERWORKSPACE &>/dev/null

while true
do
    LOADEDVERSION=$(cat $VERSIONFILE | head)

    SUBSCRIBERS=$(ls $SUBSCRIBERSTORE | awk -F'/' '{ print $NF }')
    AVAILABLEMODS=$(cat $LATESTLIST | sed 's/ //g' | sed '/^\s*$/d' | sort | uniq)

    if [[ -z "$ACTIVEVERSION" ]]
    then
        ACTIVEVERSION=$LOADEDVERSION
    fi

    if [[ "$ACTIVEVERSION" != "$LOADEDVERSION" ]]
    then
        echo "Detected new version $LOADEDVERSION"

        ACTIVEVERSION=$LOADEDVERSION

        # Reset watchlist
        for SUBSCRIBER in $SUBSCRIBERS
        do
            cp $SUBSCRIBERSTORE/$SUBSCRIBER/watchlist $SUBSCRIBERSTORE/$SUBSCRIBER/remaininglist
            cp $SUBSCRIBERWORKSPACE/$SUBSCRIBER/watchlist $SUBSCRIBERSTORE/$SUBSCRIBER/remaininglist
        done
    fi

    for SUBSCRIBER in $SUBSCRIBERS
    do
        echo "Notification service processing $SUBSCRIBER"
        # TODO: Checks

        load $SUBSCRIBER

        NOTIFIERS=$(cat $SUBSCRIBERWORKSPACE/$SUBSCRIBER/notifiers)

        for NOTIFIERDATA in $NOTIFIERS
        do
            TYPE=$(echo $NOTIFIERDATA | awk -F':' '{ print $1 }')
            SUBSCRIBERDIR=$SUBSCRIBERWORKSPACE/$SUBSCRIBER

            CMD=". $SCRIPTDIR/$TYPE $SUBSCRIBERDIR"

            eval $CMD
        done

        persist $SUBSCRIBER

        echo
    done

    echo "Sleeping $NOTIFICATIONPERIOD"
    sleep $NOTIFICATIONPERIOD
done
