#!/bin/bash

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" # http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in

source $SCRIPTDIR/utils
source $SCRIPTDIR/../CONFIG

# Takes a MODLIST and a REMAININGMODS and composes a brief message
function compose-message() {
    local MODLIST="$1"
    shift
    local REMAININGMODS="$*"

    echo "Hello,"
    echo
    # ACTIVEVERISON is passed in via the notifier
    echo "The following mod(s) from your watchlist are available on KSP $ACTIVEVERSION:"
    echo "$(tab-list "$MODLIST")"
    echo

    if [[ -z "$REMAININGMODS" ]]
    then
        echo "Your watchlist is now complete. It will be reset the next time KSP is updated."
    else
        echo "The following mod(s) remain on your watchlist:"
        echo "$(tab-list "$REMAININGMODS")"
    fi

    echo
    echo "If you run into issues, please contact @froyomuffin"
    echo "Bye!"
}

# Takes an USER and a MESSAGE then sends it out
function send-message() {
    local USER=$1
    shift
    local MESSAGE="$*"

    echo "Sending message to @$USER"

    t dm $USER "$MESSAGE"
}

function process() {
    local SUBSCRIBERDIR=$1

    echo "Processing TwitterMail for $SUBSCRIBERDIR"

    local REMAININGFILE="$SUBSCRIBERDIR/remaininglist"

    if [[ ! -e "$REMAININGFILE" ]]
    then
        local WATCHLISTFILE="$SUBSCRIBERDIR/watchlist"
        cp $WATCHLISTFILE $REMAININGFILE
    fi

    local REMAININGLIST=$(cat $REMAININGFILE | sed 's/ //g' | sed '/^\s*$/d' | sort | uniq)

    # AVAILABLEMODS is populated by the caller
    local UPDATEDMODS=$(get-common "$REMAININGLIST" "$AVAILABLEMODS")

    if [[ ! -z "$UPDATEDMODS" ]] 
    then
        echo "Updated mod(s) found!"
        echo "$(tab-list "$UPDATEDMODS")"

        NEWREMAININGLIST=$(filter-list "$REMAININGLIST" "$AVAILABLEMODS")

        USER=$(cat $SUBSCRIBERDIR/notifiers | grep '^twittermail:' | head | awk -F':' '{ print $2 }')

        if [[ ! -z "$USER" ]]
        then
            send-message $USER "$(compose-message "$UPDATEDMODS" "$NEWREMAININGLIST")"
        fi

        # Update the list of remaining mods
        echo "$NEWREMAININGLIST" > $REMAININGFILE
    fi
}

# Main
SUBSCRIBERDIR=$1
process $SUBSCRIBERDIR
