#!/bin/bash

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" # http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in

source $SCRIPTDIR/utils
source $SCRIPTDIR/../CONFIG

# Takes UPDATEDMOD and tweet that it is available!
function tweet-update() {
    UPDATEDMOD=$1
    # ACTIVEVERISON is passed in via the notifier
    MESSAGE="\"$UPDATEDMOD\" available on KSP $ACTIVEVERSION! #KSPModUpdated"
    echo "Sending '$MESSAGE'"

    #t update "$MESSAGE"
}

# Takes NEWREMAININGLIST and dispatches them for a tweet each
function tweet-updates() {
    NEWREMAININGLIST=$*

    for UPDATEDMOD in $NEWREMAININGLIST
    do
        tweet-update $UPDATEDMOD
    done
}

function process() {
    local TWITTERDIR=$1

    echo "Processing Twitter list"

    local NOTIFIEDFILE="$TWITTERDIR/notifiedlist"
    local NOTIFIEDLIST=""

    if [[ -e "$NOTIFIEDFILE" ]]
    then 
        echo "Loaded list of notified mods"
        NOTIFIEDLIST=$(cat $NOTIFIEDFILE | sed 's/ //g' | sed '/^\s*$/d' | sort | uniq)
    fi

    # AVAILABLEMODS is populated by the caller
    local NEWMODS=$(filter-list "$AVAILABLEMODS" "$NOTIFIEDLIST")

    if [[ ! -z "$NEWMODS" ]] 
    then
        echo "Updated mod(s) found!"
        echo "$(tab-list "$NEWMODS")"

        tweet-updates "$NEWMODS"

        echo "$AVAILABLEMODS" > $NOTIFIEDFILE
    fi
}

# Main
TWITTERDIR=$1
process $TWITTERDIR
