#!/bin/bash

# Persistent data
export DATASTORE="/home/tw/muffinwatcher"
export SUBSCRIBERSTORE="$DATASTORE/subscribers"
export VERSIONFILE="$DATASTORE/version"

# Transient data
export WORKSPACE="/tmp/ksp-mod-watcher"
export SUBSCRIBERWORKSPACE="$WORKSPACE/subscribers"
export LATESTLIST="$WORKSPACE/list-latest"
