#!/bin/bash

export WORKSPACE="/tmp/ksp-mod-watcher"
export USERSTORE="/tmp/ksp-mod-watcher-persistent/users"

export CKAN="$WORKSPACE/ckan"

export REFERENCEVERSION="1.0.5"
export LATESTVERSION="1.1.0"

export REFERENCELIST="$WORKSPACE/list-$REFERENCEVERSION"
export LATESTLIST="$WORKSPACE/list-$LATESTVERSION"
