#!/bin/bash

VERSION=$1
TARGET=$2

#TODO Validator

[[ -z "$VERSION" ]] || [[ -z "$TARGET" ]] && echo "Missing argument" && exit 1

NAME="$VERSION"
STUBDIR="$TARGET/$NAME"

[[ -e "$STUBDIR" ]] && echo "Stub already exists!" && exit 1

mkdir -p $STUBDIR
mkdir -p $STUBDIR/GameData

echo "Version $VERSION" >> $STUBDIR/readme.txt
