#!/bin/bash

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" # http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in

source $SCRIPTDIR/../CONFIG

# Configuration
DATAUPDATEPERIOD="900"
CKANBIN="$WORKSPACE/ckan"

CKANMETA="$WORKSPACE/CKAN-META"
CKANMETAREPO='https://github.com/KSP-CKAN/CKAN-meta.git'

URLCACHEFILE="$DATASTORE/urlcache"

# Shorten a URL using bit.ly 
function shorten() {
    local URL=$1

    # Check the short url cache
    SHORTURL=$(echo "$URLCACHE" | grep $URL)

    if [[ -z "$SHORTURL" ]]
    then
        # BITLYTOKEN variable should be set before attempting to use this
        if [[ -z "$BITLYTOKEN" ]]
        then
            return
        fi

        SHORTURL=$(curl -Ls "https://api-ssl.bitly.com/v3/shorten" \
            --data "access_token=$BITLYTOKEN" \
            --data "format=txt" \
            --data "domain=j.mp" \
            --data-urlencode "longUrl=$URL")
    fi

    # We know it's http :)
    echo $SHORTURL | sed 's/http:\/\///g'
}

function get-homepage-list() {
    cd $CKANMETA
    grep -R 'homepage' . \
        | perl -pe 's/^\.\/(.*?)\/.*\-(.*)\..*\:.*\"(.*?)\".*$/$1 $2 $3/g' \
        | sort -k1,1 -k2,2Vr \
        | awk '!a[$1]++' \
        | perl -pe 's/^(.*?) (.*?) (.*?)$/$1|$3/g'
    cd -
}

function load-urlcache() {
    if [[ -e "$URLCACHEFILE" ]]
    then
        URLCACHE="$(cat $URLCACHEFILE)"
    fi
}

function save-urlcache() {
    echo "$URLCACHE" > $URLCACHEFILE
}

function get-mod-homepage() {
    local MOD=$1

    #TODO: Find a better way to pass in the HOMEPAGELIST
    echo "$HOMEPAGELIST" | grep "^$MOD\|" | awk  -F'|' '{ print $NF }'
}

function get-short-url() {
    local MOD=$1

    # TODO: Handle rate errors
    shorten $(get-mod-homepage $MOD)
}

# Cleanup
function reset-workspace() {
    if [[ -e $CKANBIN ]]
    then
        local CKANVERSIONS=$(mono $CKANBIN ksp list | grep -v Listing | sed '/^$/d' | awk -F'"' '{ print $2 }')

        for CKANVERSION in $CKANVERSIONS
        do
            mono $CKANBIN ksp forget $CKANVERSION
        done
    fi

    rm -rf $WORKSPACE
    mkdir -p $WORKSPACE
}

function get-ckan-meta() {
    git clone $CKANMETAREPO $CKANMETA
}

function get-ckan() {
    local TARGETFILE=$1

    [[ -z "$TARGETFILE" ]] && echo "Missing argument!" && exit 1

    local LATESTURL='https://github.com/KSP-CKAN/CKAN/releases/latest'
    local VERSION=$(curl -s $LATESTURL | perl -pe 's/^.*".*\/(.*?)".*$/$1/g')

    local DLURL="https://github.com/KSP-CKAN/CKAN/releases/download/$VERSION/ckan.exe"
    echo "$DLURL to $TARGETFILE"

    wget $DLURL -O $TARGETFILE
}

# Update CKAN
function download-ckan() {
    get-ckan $CKANBIN
}

function create-stub() {
    local VERSION=$1
    local TARGET=$2

    [[ -z "$VERSION" ]] || [[ -z "$TARGET" ]] && echo "Missing argument" && exit 1

    local NAME="$VERSION"
    local STUBDIR="$TARGET/$NAME"

    [[ -e "$STUBDIR" ]] && echo "Stub already exists!" && exit 1

    mkdir -p $STUBDIR
    mkdir -p $STUBDIR/GameData

    echo "Version $VERSION" >> $STUBDIR/readme.txt
}

# Create stubs for latest and reference version installations and link them into CKAN
function create-stubs() {
    create-stub $LATESTVERSION $WORKSPACE

    mono $CKANBIN ksp add $LATESTVERSION $WORKSPACE/$LATESTVERSION
}

# Get modlist of a version
function get-modlist() {
    local VERSION=$1
    mono $CKANBIN ksp default $VERSION &>/dev/null
    mono $CKANBIN update &>/dev/null
    mono $CKANBIN available | grep '\*' | perl -pe 's/^.*? (.*?) \(.*$/$1/g'
}

# Get the modlist for latest version
function build-modlist() {
    echo "Building modlist for version: $LATESTVERSION"
    local MODLIST=$(get-modlist $LATESTVERSION)

    #TODO: Avoid this global variable
    HOMEPAGELIST="$(get-homepage-list)"

    > $LATESTLIST

    load-urlcache

    echo "Generating short urls"
    for MOD in $MODLIST
    do
        local SHORTURL=$(get-short-url $MOD)
        echo "$MOD|$SHORTURL" >> $LATESTLIST
    done

    save-urlcache
}

# Main
while true
do
    LATESTVERSION=$(cat $VERSIONFILE)

    reset-workspace
    download-ckan
    get-ckan-meta
    create-stubs
    build-modlist

    echo "Sleeping $DATAUPDATEPERIOD"
    sleep $DATAUPDATEPERIOD
done
