#!/bin/bash

#TODO: Split some variables and make directories configurable

TARGETFILE=$1

[[ -z "$TARGETFILE" ]] && echo "Missing argument!" && exit 1

LATESTURL='https://github.com/KSP-CKAN/CKAN/releases/latest'
VERSION=$(curl -s $LATESTURL | perl -pe 's/^.*".*\/(.*?)".*$/$1/g')

DLURL="https://github.com/KSP-CKAN/CKAN/releases/download/$VERSION/ckan.exe"
echo "$DLURL to $TARGETFILE"

wget $DLURL -O $TARGETFILE
