#!/bin/bash

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" # http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in

source $SCRIPTDIR/../CONFIG

# TODO: Locking

# Cleanup
function reset-workspace() {
    if [[ -e $CKAN ]]
    then
        mono $CKAN ksp forget $LATESTVERSION
        mono $CKAN ksp forget $REFERENCEVERSION
    fi

    rm -rf $WORKSPACE
    mkdir -p $WORKSPACE
}

function get-ckan() {
    local TARGETFILE=$1

    [[ -z "$TARGETFILE" ]] && echo "Missing argument!" && exit 1

    local LATESTURL='https://github.com/KSP-CKAN/CKAN/releases/latest'
    local VERSION=$(curl -s $LATESTURL | perl -pe 's/^.*".*\/(.*?)".*$/$1/g')

    local DLURL="https://github.com/KSP-CKAN/CKAN/releases/download/$VERSION/ckan.exe"
    echo "$DLURL to $TARGETFILE"

    wget $DLURL -O $TARGETFILE
}

# Update CKAN
function download-ckan() {
    get-ckan $CKAN
}

function create-stub() {
    local VERSION=$1
    local TARGET=$2

    [[ -z "$VERSION" ]] || [[ -z "$TARGET" ]] && echo "Missing argument" && exit 1

    local NAME="$VERSION"
    local STUBDIR="$TARGET/$NAME"

    [[ -e "$STUBDIR" ]] && echo "Stub already exists!" && exit 1

    mkdir -p $STUBDIR
    mkdir -p $STUBDIR/GameData

    echo "Version $VERSION" >> $STUBDIR/readme.txt
}

# Create stubs for latest and reference version installations and link them into CKAN
function create-stubs() {
    create-stub $REFERENCEVERSION $WORKSPACE
    create-stub $LATESTVERSION $WORKSPACE

    mono $CKAN ksp add $REFERENCEVERSION $WORKSPACE/$REFERENCEVERSION
    mono $CKAN ksp add $LATESTVERSION $WORKSPACE/$LATESTVERSION
}

# Get modlist of a version
function _build-modlist() {
    VERSION=$1
    mono $CKAN ksp default $VERSION &>/dev/null
    mono $CKAN update &>/dev/null
    mono $CKAN available | grep '\*' | perl -pe 's/^.*? (.*?) \(.*$/$1/g'
}

# Get the modlist for latest and reference versions
function build-modlists() {
    REFERENCELIST="$WORKSPACE/list-$REFERENCEVERSION"
    LATESTLIST="$WORKSPACE/list-$LATESTVERSION"

    _build-modlist $REFERENCEVERSION > $REFERENCELIST
    _build-modlist $LATESTVERSION > $LATESTLIST

    comm -12 $REFERENCELIST $LATESTLIST
}

# Main
TARGETFILE="/tmp/test"

while true
do
    reset-workspace
    download-ckan
    create-stubs

    DATA="$(build-modlists)"

    echo "Got"
    echo "$DATA"

    date > $TARGETFILE
    echo "<br><br>" >> $TARGETFILE

    for LINE in $DATA
    do
        echo "$LINE <br>" >> $TARGETFILE
    done

    sleep 900 # 15 Minutes
done
\
