#!/bin/bash

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" # http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in

source $SCRIPTDIR/../CONFIG

# TODO: Locking

# Cleanup
function reset-workspace() {
    if [[ -e $CKAN ]]
    then
        mono $CKAN ksp forget $LATESTVERSION
        mono $CKAN ksp forget $REFERENCEVERSION
    fi

    rm -rf $WORKSPACE
    mkdir -p $WORKSPACE
}

# Update CKAN
function download-ckan() {
    $SCRIPTDIR/get-ckan $CKAN
}

# Create stubs for latest and reference version installations and link them into CKAN
function create-stubs() {
    $SCRIPTDIR/create-stub $REFERENCEVERSION $WORKSPACE
    $SCRIPTDIR/create-stub $LATESTVERSION $WORKSPACE

    mono $CKAN ksp add $REFERENCEVERSION $WORKSPACE/$REFERENCEVERSION
    mono $CKAN ksp add $LATESTVERSION $WORKSPACE/$LATESTVERSION
}

# Get modlist of a version
function _build-modlist() {
    VERSION=$1
    mono $CKAN ksp default $VERSION &>/dev/null
    mono $CKAN update &>/dev/null
    mono $CKAN available | grep '\*' | perl -pe 's/^.*? (.*?) \(.*$/$1/g'
}

# Get the modlist for latest and reference versions
function build-modlists() {
    REFERENCELIST="$WORKSPACE/list-$REFERENCEVERSION"
    LATESTLIST="$WORKSPACE/list-$LATESTVERSION"

    _build-modlist $REFERENCEVERSION > $REFERENCELIST
    _build-modlist $LATESTVERSION > $LATESTLIST

    comm -12 $REFERENCELIST $LATESTLIST
}

# Main
TARGETFILE="/tmp/test"

while true
do
    reset-workspace
    download-ckan
    create-stubs

    DATA="$(build-modlists)"

    echo "Got"
    echo "$DATA"

    date > $TARGETFILE
    echo "<br><br>" >> $TARGETFILE

    for LINE in $DATA
    do
        echo "$LINE <br>" >> $TARGETFILE
    done

    sleep 900 # 15 Minutes
done
\
